# Generated by Django 5.2.7 on 2025-10-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Official name of the scheme', max_length=255)),
                ('description', models.TextField(help_text="Detailed description of the scheme's benefits")),
                ('eligibility', models.TextField(help_text='Who is eligible for this scheme (e.g., small farmers, SHGs)')),
                ('documents_required', models.TextField(help_text='List of documents needed to apply')),
                ('official_link', models.URLField(blank=True, max_length=500)),
                ('keywords', models.TextField(help_text='Comma-separated keywords (e.g., tractor, subsidy, loan, maharashtra)')),
            ],
        ),
    ]
